// Generated by https://quicktype.io

export interface INFTToken {
  token_address: string;
  token_id: string;
  amount: string;
  contract_type: string;
  name: null;
  symbol: null;
  token_uri: string;
  metadata: Record<string, string>;
  synced_at: string;
}
